ARG MORPHODITA_MODEL
ARG MORPHODITA_ZIP
ARG MORPHODITA_ZIP_SO

########################################################################################################################

FROM eclipse-temurin:11-jdk-alpine as unzip
ARG MORPHODITA_MODEL
ARG MORPHODITA_ZIP
COPY $MORPHODITA_MODEL .
RUN unzip $MORPHODITA_MODEL
COPY $MORPHODITA_ZIP .
RUN unzip $MORPHODITA_ZIP

FROM gradle:8.0.2-jdk11-alpine as buildMaven
ARG MORPHODITA_MODEL_TAGGER_FILE
ARG MORPHODITA_ZIP_SO
RUN mkdir annotace
WORKDIR /annotace
COPY . .
COPY --from=unzip $MORPHODITA_MODEL_TAGGER_FILE /tagger
COPY --from=unzip $MORPHODITA_ZIP_SO /lib
RUN gradle bootJar -Pcore,lemmatizer-spark,keywordextractor-ker

FROM eclipse-temurin:11-jdk-alpine as runtime
ARG MORPHODITA_MODEL_TAGGER_FILE
ARG MORPHODITA_ZIP_SO
COPY --from=buildMaven /annotace/core/build/libs/*.jar /
RUN mv *.jar annotace.jar
COPY --from=unzip $MORPHODITA_MODEL_TAGGER_FILE /
COPY --from=unzip $MORPHODITA_ZIP_SO /lib

EXPOSE 8080
ENTRYPOINT ["java","-jar","/annotace.jar"]