services:
  annotace:
    container_name: annotace
    image: annotace-morphodita
    build:
      context: .
      dockerfile: Dockerfile-morphodita
      args:
        # path to MorphoDiTa ZIP file, from https://github.com/ufal/morphodita
        MORPHODITA_ZIP: lib/morphodita-1.9.2-bin.zip
        # path to the MorphoDiTa shared library within the $MORPHODITA_ZIP
        MORPHODITA_ZIP_SO: morphodita-1.9.2-bin/bin-linux64/java/libmorphodita_java.so
    environment:
      # List of taggers mapped to individual supported languages (tagger names should correspond to files in the taggers volume)
      ANNOTACE_MORPHODITA_TAGGERS_CS: taggers/czech-morfflex2.0-pdtc1.0-220710.tagger
      ANNOTACE_LEMMATIZER: morphodita-jni
    volumes:
      - ./lib/taggers:/taggers
    ports:
      - 8888:8080
    network_mode: host
